# -*- coding: utf-8 -*-
"""EdYoda.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zH4EUjtrqZGIqXFgE2lvZYS2XefUK5a9

**Write a Python program to get the Fibonacci series between 0 to 50**

Note : The Fibonacci Sequence is the series of numbers :

0, 1, 1, 2, 3, 5, 8, 13, 21, ....

Every next number is found by adding up the two numbers before it.

Expected Output : 1 1 2 3 5 8 13 21 34
"""

a = 0
b = 1
print(a,b,end =" ")
c=a+b
while(c<50):
  print(c,end =" ")
  a=b
  b=c
  c=a+b

