# -*- coding: utf-8 -*-
"""EdYoda.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zH4EUjtrqZGIqXFgE2lvZYS2XefUK5a9

**Write a Python program that accepts a word from the user and reverse it.**



Sample Test Case



Input : Edyoda

output: adoydE
"""

word = input()
print(word[::-1])

