# -*- coding: utf-8 -*-
"""EdYoda.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zH4EUjtrqZGIqXFgE2lvZYS2XefUK5a9

**Write a Python program to count the number of even and odd numbers from a series of numbers.**

Sample numbers : numbers = (1, 2, 3, 4, 5, 6, 7, 8, 9) 
Expected Output :
Number of even numbers : 4
Number of odd numbers : 5
"""

numbers = [int(i) for i in input().split()]
even_count =odd_count=0
for i in numbers:
  if i%2 == 0:
    even_count+=1
  else:
    odd_count+=1
print("Number of even numbers:",even_count)
print("Number of odd numbers:",odd_count)

